### ISSUE TITLE
Error: Can't resolve 'style-loader/addStyles.js'

### ISSUE THREAD

**Issue by chrisblossom** [faceyspacey/extract-css-chunks-webpack-plugin#12] opened 2017-06-06 01:25 UTC
Any idea what could be causing the following error? It is only happening with a split chunk using [webpack-flush-chunks](https://github.com/faceyspacey/webpack-flush-chunks) and [react-loadable](https://github.com/thejameskyle/react-loadable/)

```
ERROR in ./src/app2.css
Module not found: Error: Can't resolve 'style-loader/addStyles.js' in '/Users/chris/github/app/src'
 @ ./src/app2.css 6:16-52
 @ ./src/app2.js
 @ ./src/app.js
 @ ./src/client.js
 @ multi client.js
```

I can setup a minimal repo if that would be helpful.

**Comment by faceyspacey** [comment] 2017-06-07 21:12
did you you fix this? Did you have `style-loader installed?

**Comment by chrisblossom** [comment] 2017-06-07 21:14
I was not able to fix this. Yes, I have ``style-loader`` installed. Would a repo help?

**Comment by faceyspacey** [comment] 2017-06-07 21:17
yea, it's basically what's needed at this point. u got the boilerplate to work right?

**Comment by chrisblossom** [comment] 2017-06-07 21:22
Yeah, boilerplate works great. I'll get a repo up shortly.

**Comment by faceyspacey** [comment] 2017-06-07 21:26
what's ur server? babel? or webpack? 

...im releasing 4 new boilerplates in a bit FYI:

-babel server
-webpack server
-babel server - flush chunk names instead of module ids
-webpack server -  flush chunk names instead of module ids

webpack made it easier to mark your split chunks with names a few weeks ago:

https://webpack.js.org/guides/code-splitting-async/#chunk-names

...but anyway, paste ur babelrc, config and code before u do much work. i may be able to assess the problem by looking at it.

**Comment by faceyspacey** [comment] 2017-06-07 21:27
my first hunch is that the issue is that you're transforming css in both babel and webpack, which won't work.

**Comment by chrisblossom** [comment] 2017-06-07 21:48
I added it back quickly so I may have missed something...but here you go:

[https://github.com/chrisblossom/react-universal-starter/tree/feature/extract-css-chunks-webpack-plugin](https://github.com/chrisblossom/react-universal-starter/tree/feature/extract-css-chunks-webpack-plugin)

**Comment by faceyspacey** [comment] 2017-06-07 21:52
i think this is it:

```js
{
        test: /\.css$/,
        exclude: /node_modules/,
        use: 'css-loader/locals?modules&localIdentName=[name]__[local]--[hash:base64:5]'
      }
```

i happened to have just marked it as HELPED WANTED on the extract-css-chunks-webpack-plugin repo a few minutes ago:

https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/issues/5

**Comment by faceyspacey** [comment] 2017-06-07 21:53
...i.e. changed this to the old way i pasted above:

https://github.com/chrisblossom/react-universal-starter/blob/feature/extract-css-chunks-webpack-plugin/tools/webpack/server.js#L96

**Comment by chrisblossom** [comment] 2017-06-07 21:55
Wait, the server isn't using the ``extract-css-chunks-webpack-plugin``  but instead ``css-loader/locals`` as mentioned in your boilerplate.

**Comment by chrisblossom** [comment] 2017-06-07 21:55
https://github.com/chrisblossom/react-universal-starter/blob/feature/extract-css-chunks-webpack-plugin/tools/webpack/client.js#L108

**Comment by faceyspacey** [comment] 2017-06-07 22:00
then u may *HAVE* to use extract-css-chunks-webpack-plugin. let me know if switching it works.

**Comment by faceyspacey** [comment] 2017-06-07 22:10
...in the webpack server boilerplate, i just tried using the original extract text plugin and it worked. hmm. ...if u wanna use the original plugin, my guess is it's one of the following:

this line:
https://github.com/chrisblossom/react-universal-starter/blob/feature/extract-css-chunks-webpack-plugin/tools/webpack/client.js#L193

is actually [contenthash] not [chunkhash]. ...contenthash is what's used in the extract text plugin, not the chunkhash.

the other thing is u may have to specifying in the options here:
https://github.com/chrisblossom/react-universal-starter/blob/feature/extract-css-chunks-webpack-plugin/tools/webpack/client.js#L110
`fallback: 'style-loader'`. ..i just needed to make that change to avoid the react checksums mismatch error.

**Comment by chrisblossom** [comment] 2017-06-07 22:10
I was not able to get it to work by adding it to the server. Also I just checked, boilerplate works as expected with ``css-loader/locals`` and the new object-config type on the server.

I must have something wrong in my config that is conflicting...

If you happen to start up the boilerplate, create a file called ``.env`` and put ``HMR=false`` inside so it will disable ``browsersync``

**Comment by faceyspacey** [comment] 2017-06-07 22:13
also im not sure `[contenthash]` hash in this case takes a parameter, i.e. `[contenthash:8]` may not work. so try it without first. but let me know if `:8` actually truncates the hash. there's no documentation of it being available here.

**Comment by chrisblossom** [comment] 2017-06-08 03:15
Using ``contenthash`` fixed a different issue I was having, but still am getting the same error.

The ``:8`` is from [create-react-app/webpack.config.prod.js](https://github.com/facebookincubator/create-react-app/blob/f6d85440335ba61c828cfb30259b2ecb91c3da2d/packages/react-scripts/config/webpack.config.prod.js#L46). They are usually really good at using stable features/sane defaults. I tried it without it and still the same error.

Also, to be clear, I'm not using the original extract text plugin anywhere in in this branch.

I am at a loss what I am doing wrong here when comparing it to your boilerplate.

Thank you for your help!

**Comment by faceyspacey** [comment] 2017-06-08 03:25
try upgrading extract-css-chunks-webpackplugin. i made a few updates earlier. im not sure how u got the object type to work (and I know ur not using it), but for me i had to make a few changes to get it to work. it seemed to accidentally work. maybe u'll get lucky too once u update.

...fyi: u dont need the allChunks option or the fallback (as there is no choice here). ..that said, i just tried *adding* both to my boilerplate and they didn't cause a problem. so thats not it either

....my gut says this is gonna be one of those things that turn out to be really small and stupid.

**Comment by chrisblossom** [comment] 2017-06-08 03:30
I agree it is probably something small and stupid...

I tried commenting out the allChunks to test earlier and it didn't change anything.

I never got the object type to work, only with the original plugin. I just updated and same issue. It is looking like it isn't looking in ``node_modules`` for style-loader, but instead my ``src`` directory, BUT only for the added chunk. The first chunk works as expected.

**Comment by faceyspacey** [comment] 2017-06-08 03:31
...since it's hard to run compilation through a debugger, dig into your node_modules and find this package and put logging around these lines:

https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/15833007a06883ee4a34db324a9bc02479a27613/loader.js#L20

https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/15833007a06883ee4a34db324a9bc02479a27613/loader.js#L141


...can you require anything from `style-loader`? ...truth is i've had similar errors 2 months ago when i was working on this. i forget what it typically is though. but i know something fishy goes on here.

**Comment by faceyspacey** [comment] 2017-06-08 03:31
...the object type doesn't work? ..what version appears in package.json? "^1.0.12"?

**Comment by chrisblossom** [comment] 2017-06-08 03:32
I haven't tried the object type yet, sorry for the confusion.

**Comment by faceyspacey** [comment] 2017-06-08 03:32
here's how it should look:

```
{
        test: /\.css$/,
        use: ExtractCssChunks.extract({
          use: {
            loader: 'css-loader',
            options: {
              modules: true,
              localIdentName: '[name]__[local]--[hash:base64:5]'
            }
          }
        })
      }
```

**Comment by chrisblossom** [comment] 2017-06-08 03:34
Just tried it with and without the fallback. Still no luck.

**Comment by faceyspacey** [comment] 2017-06-08 03:41
im getting this error with the repo: ```Error: Failed to replace env in config: ${NPM_TOKEN}```

**Comment by faceyspacey** [comment] 2017-06-08 03:42
ok, i just deleted what was in your npmrc.

**Comment by faceyspacey** [comment] 2017-06-08 03:44
im getting the following error when i do `npm start`:

```
Jamess-MacBook-Pro:react-universal-starter jamesgillmore$ npm start

> react-universal-starter@1.0.0 start /Users/jamesgillmore/React/react-universal-starter
> babel-node tools/run start

[20:43:14] Info: Starting 'start:development'...
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn redis-server ENOENT
    at exports._errnoException (util.js:1033:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by chrisblossom** [comment] 2017-06-08 03:46
Comment out [tools/start.js#L66-L70](https://github.com/chrisblossom/react-universal-starter/blob/feature/extract-css-chunks-webpack-plugin/tools/start.js#L66-L70).

Sorry, I put this up in a hurry. It is because you don't have ``redis`` installed locally.

**Comment by faceyspacey** [comment] 2017-06-08 03:46
k, workin on it

**Comment by faceyspacey** [comment] 2017-06-08 03:49
npm start worked perfectly for me, here's the output source:

```

<!DOCTYPE html><html lang="en-US"><head><title>react-safe-universal-inputs demo</title><link href="/dist/main.1419ee4a.css" media="screen, projection" rel="stylesheet" type="text/css" charset="UTF-8"/><link rel="preload" href="/dist/bootstrap.js" as="script"/><link rel="preload" href="/dist/0.fd0b425b.js" as="script"/><link rel="preload" href="/dist/main.e08df160.js" as="script"/></head><body><br/><br/><br/><br/><br/><div id="root"><div data-reactroot="" data-reactid="1" data-react-checksum="266022379"><!-- react-text: 2 -->app1<!-- /react-text --><div class="app___3Uev9" data-reactid="3">app2</div></div></div><script src="/dist/vendor.dll.js" defer="" charset="UTF-8"></script><script src="/dist/bootstrap.js" type="text/javascript" defer=""></script><script src="/dist/0.fd0b425b.js" type="text/javascript" defer=""></script><script src="/dist/main.e08df160.js" type="text/javascript" defer=""></script></body></html>
```

**Comment by chrisblossom** [comment] 2017-06-08 03:49
If you are on Discord's reactiflux server, I'm @chrisblossom#0865.

**Comment by faceyspacey** [comment] 2017-06-08 03:50
im not i only vaguely know what discord is lol

**Comment by chrisblossom** [comment] 2017-06-08 03:51
Are you on the correct branch of the repo? The master works as expected using the original extract plugin.

**Comment by chrisblossom** [comment] 2017-06-08 03:51
I'm on Slack too, just no idea what server.

**Comment by faceyspacey** [comment] 2017-06-08 03:52
oh ok. what branch? ...im on imessage as faceyspacey@icloud.com and jamesgillmore@gmail.com for gchat

**Comment by chrisblossom** [comment] 2017-06-08 03:54
``extract-css-chunks-webpack-plugin`` branch. gchat/hangout invite sent

**Comment by faceyspacey** [comment] 2017-06-08 03:59
...for some reason, i didnt get the invite. email me. maybe we can trigger a chat from there.

**Comment by faceyspacey** [comment] 2017-06-08 04:05
here's the resulting output where it worked. ...ur doing some weird things with links to js files in ur head, but maybe that's something ur workin on:

```
<!DOCTYPE html>
<html lang="en-US">

<head>
    <title>react-safe-universal-inputs demo</title>
    <link href="/dist/0.11f9f9ce.css" media="screen, projection" rel="stylesheet" type="text/css" charset="UTF-8" />
    <link rel="preload" href="/dist/bootstrap.no_css.js" as="script" />
    <link rel="preload" href="/dist/0.2de3be6d.no_css.js" as="script" />
    <link rel="preload" href="/dist/main.99ea5756.no_css.js" as="script" />
</head>

<body>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <div id="root">
        <div data-reactroot="" data-reactid="1" data-react-checksum="266022379">
            <!-- react-text: 2 -->app1
            <!-- /react-text -->
            <div class="app___3Uev9" data-reactid="3">app2</div>
        </div>
    </div>
    <script src="/dist/vendor.dll.js" defer="" charset="UTF-8"></script>
    <script src="/dist/bootstrap.no_css.js" type="text/javascript" defer=""></script>
    <script src="/dist/0.2de3be6d.no_css.js" type="text/javascript" defer=""></script>
    <script src="/dist/main.99ea5756.no_css.js" type="text/javascript" defer=""></script>
</body>

</html>
```

**Closed by faceyspacey** 2017-06-08 04:05 UTC

**Comment by chrisblossom** [comment] 2017-06-08 04:47
http://caniuse.com/#feat=link-rel-preload
From what I understand, the preload tells the (newer) browsers to start downloading the files before it gets to the actual ``<script`` tags. Then ``defer`` tells the browser it doesn't need the scripts for the page to be done, but execute them in the order specified.

FYI, ``defer`` does not as expected with Internet Explorer.

**Comment by faceyspacey** [comment] 2017-06-08 05:08
personally i wouldn't mess with that stuff yet. support is so minimal. i haven't seen it remotely become common. there's been like 1 article in the javascript news sites in the past year.
